apiVersion: policy.jspolicy.com/v1beta1
kind: JsPolicy
metadata:
  name: enforce-reloader-annotations.anza-labs.dev
spec:
  operations: [CREATE, UPDATE]
  resources:
    - deployments
    - statefulsets
    - daemonsets
  scope: Namespaced
  type: Mutating
