name: jspolicy-lint-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ./jspolicy/package.json
      - working-directory: ./jspolicy
        run: npm install --include=dev
      - working-directory: ./jspolicy
        run: npm run format-check

  test:
    runs-on: ubuntu-latest
    needs:
      - format
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ./jspolicy/package.json
      - working-directory: ./jspolicy
        run: npm install --include=dev
      - working-directory: ./jspolicy
        run: npm test
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  compile:
    runs-on: ubuntu-latest
    needs:
      - format
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: ./jspolicy/package.json
      - working-directory: ./jspolicy
        run: npm install --include=dev
      - working-directory: ./jspolicy
        run: npm run compile
      - uses: actions/upload-artifact@v4
        with:
          name: policies
          path: 'jspolicy/policies/*'
          retention-days: 7

  e2e:
    runs-on: ubuntu-latest
    needs:
      - test
      - compile
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - uses: azure/setup-helm@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/download-artifact@v4
      - run: |
          make \
            cluster deploy
      - run: |
          make \
            test-e2e
