name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-please-config.json

    # JSPolicy
      - if: ${{ steps.release.outputs.jspolicy--release_created }}
        uses: actions/checkout@v4
      - if: ${{ steps.release.outputs.jspolicy--release_created }}
        uses: actions/setup-node@v4
        with:
          node-version-file: ./jspolicy/package.json
      - if: ${{ steps.release.outputs.jspolicy--release_created }}
        working-directory: ./jspolicy
        run: npm install --include=dev
      - if: ${{ steps.release.outputs.jspolicy--release_created }}
        working-directory: ./jspolicy
        run: |
          npm run compile
      - if: ${{ steps.release.outputs.jspolicy--release_created }}
        uses: softprops/action-gh-release@v2
        with:
          files: ./jspolicy/dist/bundle.tar.gz
          tag_name: ${{ steps.release.outputs.jspolicy--tag_name }}
